# -*- coding: utf-8 -*-
"""PrimerParcial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ywv3LO7rn3TcMjRzZq7MWpH95wyh6Alu
"""

#Importando librerias
import os
import numpy as np
from matplotlib import pyplot
import pandas as pd

#Conectando con Drive
from google.colab import drive
drive.mount('/content/drive')

"""DATA SET USADO #198 https://www.kaggle.com/datasets/mariyamalshatta/inn-hotels-group/"""

#Importando dataset
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/INNHotelsGroup.csv')
data.info()

""" Insertar atributos que contengan caracteres, texto y
 valores booleanos
"""

#Agrega caracteres en la columna tipo de cuarto
Groups = ['A', 'B', 'C', 'D']
data['Tipo de Cuarto'] = np.random.choice(Groups, size=len(data))

# Agregar una nueva columna de texto "Comentarios" con valores de comentarios predeterminados
feedback_texts = ['¡Gran servicio!', 'La habitación no estaba limpia.', 'Volvería otra vez.', '¡Tuve una estancia fantástica!', 'No vale el precio.']
# Agrega randomicamente comentarios a cada huesped
data['Comentarios'] = np.random.choice(feedback_texts, size=len(data))

# Agregue una nueva columna booleana "VIP_Guest" basada en la cantidad de reservas anteriores no canceladas
data['VIP'] = np.where(data['no_of_previous_bookings_not_canceled'] > 2, True, False)

# Mostrar el conjunto de datos modificado con las nuevas columnas
print(data.head())